### ISSUE TITLE
importing from package index causes errors in Vercel serverless functions

### ISSUE THREAD

**Issue by joelhooks** [skillrecordings/products#107]
Initial user report of a `500` error answering a quiz question in the `compilers-for-humans` app:

![image](https://user-images.githubusercontent.com/86834/136463610-ae866a00-ac6f-441c-837f-1b2ad7b831b0.png)

Was **unable** to reproduce in dev, but in prod and preview environments discovered the error in the function logs:

```bash
[GET] /api/answer

2021-10-07T13:31:59.113Z	89cb340f-0b78-458f-a3b0-8766f2b18553	ERROR	Error: Cannot find module 'lodash/isPlainObject'
Require stack:
- /var/task/node_modules/.pnpm/formik@2.2.9_react@17.0.2/node_modules/formik/dist/formik.cjs.production.min.js
- /var/task/node_modules/.pnpm/formik@2.2.9_react@17.0.2/node_modules/formik/dist/index.js
- /var/task/apps/compilersforhumans/.next/server/pages/api/answer.js
- /var/task/node_modules/.pnpm/next@11.0.1_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/next/dist/next-server/server/next-server.js
- /var/task/apps/compilersforhumans/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/formik@2.2.9_react@17.0.2/node_modules/formik/dist/formik.cjs.production.min.js:1:227)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/.pnpm/formik@2.2.9_react@17.0.2/node_modules/formik/dist/formik.cjs.production.min.js',
    '/var/task/node_modules/.pnpm/formik@2.2.9_react@17.0.2/node_modules/formik/dist/index.js',
    '/var/task/apps/compilersforhumans/.next/server/pages/api/answer.js',
    '/var/task/node_modules/.pnpm/next@11.0.1_f31b35bdaa3b7c2fce82404f09d2dac4/node_modules/next/dist/next-server/server/next-server.js',
    '/var/task/apps/compilersforhumans/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
RequestId: 89cb340f-0b78-458f-a3b0-8766f2b18553 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

The error points to the `formik` library, which **is not used in the serverless function** but exists in the `@skillrecordings/quiz` package React components.

Working through past preview deploys, found one that was working from 3 days prior, but **redeploying the last know working snapshot resulted in a preview deploy that gave the same error**

Changed the versions of `formik` that we were using across the app.

Changed some other library versions to the latest explicitly as well.

Migrated the `answer` function into the engineering management app instead of importing it and the error changed. Now it threw:

![image](https://user-images.githubusercontent.com/86834/136464098-b3e76185-52f8-40c5-9333-470f1dbaf654.png)

Migrated the utility function from the `convertkit` package (which also uses formik and yup) and **this caused the issue to cease**

![tell us more](https://media.giphy.com/media/Tt9jctxaVjRny/giphy.gif)

OK

reverted all the direct code and imported the serverless function from quiz using `@skillrecordings/quiz/dist/pages/api/answer` and the `yup` error persisted

in the `answer` function changed the import of the util to `@skillrecordings/convertkit/dist/utils/fetch-convertkit-subscriber` and **everything seems to work**

importing from the root `index` seems to cause issues with the serverless function.

no ideas about root cause yet and it doesn't appear to be a change on our side.

**Comment by joelhooks** [comment]
```
Hi Joel,

Sorry for the trouble here, we're working on making the required changes so that doesn't happen in the future.

Are you able to try the proposed change by using the canary version of Next.js and then use this next.config.js?
module.exports = {
  experimental: {
    outputFileTracing: true
  }
}

If this doesn't work for you then please let us know.

Matthew Sweeney
▲ Director of Customer Success at Vercel
```
